# Generated by Django 3.1.5 on 2021-01-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210119_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post_image',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_image',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
